# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dca9817a4dd4e2fff76518e300f3e355e9e4260db25dc38bf939df406ab6e5771411515bc01fc01e6e4505669cd2af42f39ad50ade735fcc82738a2811d2f904

test:
  secret_key_base: 252ce83e6d282429a71570d84ffae03bc3b1d5286e6e629420b97f8ce0d87a7888274bdf618edf9c28a26c6b215d75f674465dd3e5e0dc8a964bd14d72e9897b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
